version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    ports:
      - "3333:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  testng-module:
    image: priya2298/selenium-docker
    depends_on: 
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST= hub
      - MODULE=testng.xml
    volumes:
      - ./output/testng-result:/usr/selenium/testng-output
